-- Peony — mevcut site içeriğinin Supabase'e aktarımı
-- schema.sql çalıştırıldıktan SONRA bir kez çalıştırın.

insert into peony_content (key, value) values
  ('about.cta', '{"th": "ชมบรรยากาศ", "en": "See the space", "tr": "Mekânı gör", "ru": "Посмотреть салон", "zh": "看看环境", "hi": "जगह देखें"}'::jsonb),
  ('about.eyebrow', '{"th": "เกี่ยวกับ Peony", "en": "About Peony", "tr": "Peony Hakkında", "ru": "О Peony", "zh": "关于 Peony", "hi": "Peony के बारे में"}'::jsonb),
  ('about.stat1', '{"th": "ปีแห่งประสบการณ์", "en": "Years of practice", "tr": "Yıllık deneyim", "ru": "Лет практики", "zh": "年从业经验", "hi": "वर्षों का अनुभव"}'::jsonb),
  ('about.stat2', '{"th": "นักบำบัดที่ได้รับใบรับรอง", "en": "Certified therapists", "tr": "Sertifikalı terapist", "ru": "Сертифицированных мастеров", "zh": "位持证理疗师", "hi": "प्रमाणित थेरेपिस्ट"}'::jsonb),
  ('about.stat3', '{"th": "ลูกค้าที่เราได้ต้อนรับ", "en": "Guests welcomed", "tr": "Ağırlanan misafir", "ru": "Принятых гостей", "zh": "位到访客人", "hi": "मेहमानों का स्वागत"}'::jsonb),
  ('about.text', '{"th": "Peony เป็นสปาไทยเล็ก ๆ ที่สร้างขึ้นจากความเชื่อเดียว — การพักผ่อนที่แท้จริงเร่งรีบไม่ได้ นักบำบัดของเราผ่านการฝึกศาสตร์การนวดแผนไทยดั้งเดิม ทำงานด้วยน้ำมันอุ่น ลูกประคบสมุนไพร และแรงกดที่สม่ำเสมอ ในห้องที่เราตั้งใจรักษาความเงียบไว้", "en": "Peony is a small Thai spa built around one idea — that real rest cannot be rushed. Our therapists are trained in traditional Thai technique and work with warm oils, herbal compresses and steady pressure, in rooms kept deliberately quiet.", "tr": "Peony tek bir fikir üzerine kurulmuş küçük bir Tayland spası: gerçek dinlenme acele edilerek olmaz. Terapistlerimiz geleneksel Tayland tekniğinde eğitimli; sıcak yağlar, bitkisel kompresler ve dengeli basınçla, bilinçli olarak sessiz tutulan odalarda çalışıyorlar.", "ru": "Peony — небольшой тайский спа, построенный вокруг одной мысли: настоящий отдых не терпит спешки. Наши мастера обучены традиционной тайской технике и работают с тёплыми маслами, травяными компрессами и ровным давлением — в кабинетах, где намеренно сохраняется тишина.", "zh": "Peony 是一家小而专注的泰式水疗馆，只围绕一个信念——真正的休息急不来。我们的理疗师受过传统泰式手法训练，以温热精油、草药热敷包与稳定而均匀的力度施作，房间始终刻意保持安静。", "hi": "Peony एक छोटा थाई स्पा है, जो एक ही विचार पर टिका है — असली आराम जल्दी में नहीं मिलता। हमारे थेरेपिस्ट पारंपरिक थाई तकनीक में प्रशिक्षित हैं और गर्म तेल, हर्बल कंप्रेस तथा संतुलित दबाव के साथ काम करते हैं, ऐसे कमरों में जिन्हें जानबूझकर शांत रखा जाता है।"}'::jsonb),
  ('about.title1', '{"th": "การดูแลที่สงบ", "en": "A calm, unhurried", "tr": "Sakin, aceleye", "ru": "Спокойный, неторопливый", "zh": "从容、不急不躁的", "hi": "शांत और बिना"}'::jsonb),
  ('about.title2', '{"th": "และไม่เร่งรีบ", "en": "kind of care", "tr": "gelmeyen bir bakım", "ru": "уход", "zh": "照护", "hi": "जल्दबाज़ी की देखभाल"}'::jsonb),
  ('band.eyebrow', '{"th": "ห้องบำบัด", "en": "The Room", "tr": "Oda", "ru": "Кабинет", "zh": "理疗室", "hi": "कमरा"}'::jsonb),
  ('band.quote', '{"th": "แสงสลัว ผ้าขนหนูอุ่น และไม่มีนาฬิกาบนผนัง", "en": "Low light, warm towels, and no clock on the wall.", "tr": "Loş ışık, sıcak havlular ve duvarda saat yok.", "ru": "Приглушённый свет, тёплые полотенца и ни одних часов на стене.", "zh": "灯光柔和，毛巾温热，墙上没有钟。", "hi": "मद्धिम रोशनी, गर्म तौलिए, और दीवार पर कोई घड़ी नहीं।"}'::jsonb),
  ('contact.address', '{"th": "ที่อยู่", "en": "Address", "tr": "Adres", "ru": "Адрес", "zh": "地址", "hi": "पता"}'::jsonb),
  ('contact.eyebrow', '{"th": "ติดต่อเรา", "en": "Contact", "tr": "İletişim", "ru": "Контакты", "zh": "联系我们", "hi": "संपर्क"}'::jsonb),
  ('contact.form.date', '{"th": "วันที่ต้องการ", "en": "Preferred date", "tr": "Tercih ettiğiniz tarih", "ru": "Желаемая дата", "zh": "期望日期", "hi": "पसंदीदा तारीख़"}'::jsonb),
  ('contact.form.name', '{"th": "ชื่อ-นามสกุล", "en": "Full name", "tr": "Ad soyad", "ru": "Имя и фамилия", "zh": "姓名", "hi": "पूरा नाम"}'::jsonb),
  ('contact.form.namePh', '{"th": "ชื่อของคุณ", "en": "Your name", "tr": "Adınız", "ru": "Ваше имя", "zh": "你的称呼", "hi": "आपका नाम"}'::jsonb),
  ('contact.form.note', '{"th": "เราจะยืนยันทางโทรศัพท์หรือข้อความ ไม่มีการเก็บเงินผ่านเว็บไซต์", "en": "We will confirm by phone or message. No payment is taken online.", "tr": "Telefon ya da mesajla teyit ediyoruz. Çevrim içi ödeme alınmaz.", "ru": "Мы подтвердим по телефону или в сообщении. Оплата онлайн не взимается.", "zh": "我们会以电话或短信确认，网站上不收取任何费用。", "hi": "हम फ़ोन या संदेश से पुष्टि करेंगे। ऑनलाइन कोई भुगतान नहीं लिया जाता।"}'::jsonb),
  ('contact.form.notes', '{"th": "สิ่งที่เราควรทราบ", "en": "Anything we should know", "tr": "Bilmemiz gereken bir şey", "ru": "Что нам стоит знать", "zh": "需要我们注意的事", "hi": "कुछ जो हमें जानना चाहिए"}'::jsonb),
  ('contact.form.notesPh', '{"th": "อาการบาดเจ็บ น้ำหนักมือที่ชอบ มาครั้งแรก…", "en": "Injuries, pressure preference, first visit…", "tr": "Sakatlık, basınç tercihi, ilk ziyaret…", "ru": "Травмы, предпочтения по нажиму, первый визит…", "zh": "旧伤、力度偏好、首次到访……", "hi": "चोट, दबाव की पसंद, पहली बार…"}'::jsonb),
  ('contact.form.phone', '{"th": "เบอร์โทรศัพท์", "en": "Phone", "tr": "Telefon", "ru": "Телефон", "zh": "电话", "hi": "फ़ोन"}'::jsonb),
  ('contact.form.phonePh', '{"th": "เบอร์ที่ติดต่อคุณได้สะดวก", "en": "Best number to reach you", "tr": "Size ulaşabileceğimiz numara", "ru": "Номер, по которому удобно связаться", "zh": "方便联系你的号码", "hi": "जिस नंबर पर संपर्क करें"}'::jsonb),
  ('contact.form.sent', '{"th": "ขอบคุณค่ะ — เราได้รับคำขอของคุณแล้ว และจะติดต่อกลับในไม่ช้า", "en": "Thank you — your request has been noted. We will be in touch shortly.", "tr": "Teşekkürler — talebiniz alındı. Kısa süre içinde size dönüş yapacağız.", "ru": "Спасибо — заявка принята. Мы свяжемся с вами в ближайшее время.", "zh": "谢谢——已收到你的请求，我们会尽快与你联系。", "hi": "धन्यवाद — आपका अनुरोध मिल गया है। हम जल्दी ही संपर्क करेंगे।"}'::jsonb),
  ('contact.form.service', '{"th": "บริการที่ต้องการ", "en": "Treatment", "tr": "Uygulama", "ru": "Процедура", "zh": "理疗项目", "hi": "उपचार"}'::jsonb),
  ('contact.form.servicePick', '{"th": "เลือกบริการ", "en": "Choose a treatment", "tr": "Bir uygulama seçin", "ru": "Выберите процедуру", "zh": "请选择项目", "hi": "एक उपचार चुनें"}'::jsonb),
  ('contact.form.submit', '{"th": "ส่งคำขอ", "en": "Send request", "tr": "Talebi gönder", "ru": "Отправить заявку", "zh": "发送请求", "hi": "अनुरोध भेजें"}'::jsonb),
  ('contact.form.time', '{"th": "เวลาที่ต้องการ", "en": "Preferred time", "tr": "Tercih ettiğiniz saat", "ru": "Желаемое время", "zh": "期望时间", "hi": "पसंदीदा समय"}'::jsonb),
  ('contact.formTitle', '{"th": "ส่งคำขอนัดหมาย", "en": "Request an appointment", "tr": "Randevu talebi oluşturun", "ru": "Заявка на запись", "zh": "提交预约请求", "hi": "अपॉइंटमेंट का अनुरोध"}'::jsonb),
  ('contact.hours', '{"th": "เวลาทำการ", "en": "Opening hours", "tr": "Çalışma saatleri", "ru": "Часы работы", "zh": "营业时间", "hi": "खुलने का समय"}'::jsonb),
  ('contact.mapNote', '{"th": "แผนที่ — -doldurulacak-", "en": "Map — -doldurulacak-", "tr": "Harita — -doldurulacak-", "ru": "Карта — -doldurulacak-", "zh": "地图 — -doldurulacak-", "hi": "नक़्शा — -doldurulacak-"}'::jsonb),
  ('contact.phone', '{"th": "โทรศัพท์ &amp; อีเมล", "en": "Phone & email", "tr": "Telefon &amp; e-posta", "ru": "Телефон &amp; почта", "zh": "电话 &amp; 邮箱", "hi": "फ़ोन &amp; ईमेल"}'::jsonb),
  ('contact.text', '{"th": "ส่งคำขอด้านล่าง แล้วเราจะยืนยันการนัดหมายให้ในเวลาไม่นาน หรือโทรหาเราโดยตรงในเวลาทำการก็ได้", "en": "Send a request below and we will confirm your appointment shortly, or simply call us during opening hours.", "tr": "Aşağıdan talebinizi gönderin, randevunuzu kısa sürede teyit edelim; ya da açık olduğumuz saatlerde doğrudan arayın.", "ru": "Отправьте заявку ниже, и мы вскоре подтвердим запись; или просто позвоните нам в рабочие часы.", "zh": "在下方提交预约请求，我们会尽快为你确认；也可以在营业时间内直接致电。", "hi": "नीचे अनुरोध भेजिए, हम जल्दी ही आपका अपॉइंटमेंट पक्का कर देंगे; या खुलने के समय में सीधे फ़ोन कर लीजिए।"}'::jsonb),
  ('contact.title', '{"th": "แวะมาหาเราได้เลย", "en": "Come and find us", "tr": "Gelin, bizi bulun", "ru": "Приходите — мы рядом", "zh": "欢迎前来", "hi": "आइए, हमें ढूँढिए"}'::jsonb),
  ('faq.eyebrow', '{"th": "เรื่องที่ควรรู้", "en": "Good to Know", "tr": "Bilmekte Fayda Var", "ru": "Полезно знать", "zh": "预约须知", "hi": "जानना ज़रूरी है"}'::jsonb),
  ('faq.title', '{"th": "คำถามที่พบบ่อย", "en": "Frequently asked questions", "tr": "Sık sorulan sorular", "ru": "Частые вопросы", "zh": "常见问题", "hi": "अक्सर पूछे जाने वाले प्रश्न"}'::jsonb),
  ('foot.ctaBtn', '{"th": "จองคิว", "en": "Book Appointment", "tr": "Randevu Al", "ru": "Записаться", "zh": "立即预约", "hi": "अपॉइंटमेंट लें"}'::jsonb),
  ('foot.ctaCall', '{"th": "โทรหาเรา", "en": "Call us", "tr": "Bizi arayın", "ru": "Позвонить нам", "zh": "致电我们", "hi": "हमें कॉल करें"}'::jsonb),
  ('foot.ctaEyebrow', '{"th": "การจอง", "en": "Reservations", "tr": "Rezervasyon", "ru": "Запись", "zh": "预约", "hi": "बुकिंग"}'::jsonb),
  ('foot.ctaText', '{"th": "เรายินดีต้อนรับลูกค้า walk-in เมื่อมีคิวว่าง แต่การจองล่วงหน้าหมายความว่าห้อง นักบำบัด และเวลา เป็นของคุณเรียบร้อยแล้ว", "en": "Walk-ins are welcome when we have space, but booking ahead means the room, the therapist and the time are already yours.", "tr": "Yer olduğunda randevusuz misafirlerimizi de ağırlıyoruz; ama önceden randevu almak oda, terapist ve saatin baştan sizin olması demek.", "ru": "Мы рады гостям без записи, когда есть свободное время, но предварительная запись означает, что кабинет, мастер и час уже ваши.", "zh": "有空档时我们也欢迎直接到店，但提前预约意味着房间、理疗师与时间从一开始就属于你。", "hi": "जगह होने पर बिना बुकिंग आने वालों का भी स्वागत है, पर पहले से बुक करने का मतलब है कि कमरा, थेरेपिस्ट और समय पहले से ही आपके हैं।"}'::jsonb),
  ('foot.ctaTitle', '{"th": "กันเวลาสักชั่วโมงไว้ให้ตัวเอง", "en": "Keep an hour for yourself", "tr": "Kendinize bir saat ayırın", "ru": "Оставьте час для себя", "zh": "为自己留一小时", "hi": "एक घंटा अपने लिए रखिए"}'::jsonb),
  ('foot.follow', '{"th": "ติดตามเรา", "en": "Follow", "tr": "Takip edin", "ru": "Мы в соцсетях", "zh": "关注我们", "hi": "फ़ॉलो करें"}'::jsonb),
  ('foot.hours', '{"th": "เวลาทำการ", "en": "Opening hours", "tr": "Çalışma saatleri", "ru": "Часы работы", "zh": "营业时间", "hi": "खुलने का समय"}'::jsonb),
  ('foot.rights', '{"th": "© 2026 Peony Thai Massage &amp; Spa สงวนลิขสิทธิ์", "en": "© 2026 Peony Thai Massage &amp; Spa. All rights reserved.", "tr": "© 2026 Peony Thai Massage &amp; Spa. Tüm hakları saklıdır.", "ru": "© 2026 Peony Thai Massage &amp; Spa. Все права защищены.", "zh": "© 2026 Peony Thai Massage &amp; Spa 版权所有。", "hi": "© 2026 Peony Thai Massage &amp; Spa. सर्वाधिकार सुरक्षित।"}'::jsonb),
  ('foot.visit', '{"th": "แวะมา &amp; โทรหา", "en": "Visit &amp; call", "tr": "Ziyaret &amp; arama", "ru": "Адрес &amp; телефон", "zh": "到店 &amp; 致电", "hi": "पता &amp; फ़ोन"}'::jsonb),
  ('foot.weekdays', '{"th": "จันทร์ – ศุกร์", "en": "Monday – Friday", "tr": "Pazartesi – Cuma", "ru": "Понедельник – пятница", "zh": "周一 – 周五", "hi": "सोमवार – शुक्रवार"}'::jsonb),
  ('foot.weekend', '{"th": "เสาร์ – อาทิตย์", "en": "Saturday – Sunday", "tr": "Cumartesi – Pazar", "ru": "Суббота – воскресенье", "zh": "周六 – 周日", "hi": "शनिवार – रविवार"}'::jsonb),
  ('gal.cta', '{"th": "ดูแกลเลอรีทั้งหมด", "en": "View full gallery", "tr": "Tüm galeriyi gör", "ru": "Смотреть всю галерею", "zh": "查看完整相册", "hi": "पूरी गैलरी देखें"}'::jsonb),
  ('gal.eyebrow', '{"th": "แกลเลอรี", "en": "Gallery", "tr": "Galeri", "ru": "Галерея", "zh": "环境相册", "hi": "गैलरी"}'::jsonb),
  ('gal.title', '{"th": "มองเข้ามาข้างใน", "en": "A look inside", "tr": "İçeriden bir bakış", "ru": "Взгляд изнутри", "zh": "走进来看看", "hi": "अंदर की एक झलक"}'::jsonb),
  ('gallery.all', '{"th": "ทั้งหมด", "en": "All", "tr": "Tümü", "ru": "Всё", "zh": "全部", "hi": "सभी"}'::jsonb),
  ('gallery.details', '{"th": "รายละเอียด", "en": "Details", "tr": "Detaylar", "ru": "Детали", "zh": "细节", "hi": "बारीकियाँ"}'::jsonb),
  ('gallery.eyebrow', '{"th": "แกลเลอรี", "en": "Gallery", "tr": "Galeri", "ru": "Галерея", "zh": "环境相册", "hi": "गैलरी"}'::jsonb),
  ('gallery.space', '{"th": "บรรยากาศ", "en": "The space", "tr": "Mekân", "ru": "Интерьер", "zh": "空间", "hi": "जगह"}'::jsonb),
  ('gallery.text', '{"th": "ช่วงเวลาบางส่วนจากภายใน Peony — ห้องบำบัด พิธีกรรมเล็ก ๆ และมุมเงียบระหว่างนั้น", "en": "A few moments from inside Peony — the treatment rooms, the small rituals, and the quiet corners in between.", "tr": "Peony''nin içinden birkaç an — uygulama odaları, küçük ritüeller ve aradaki sessiz köşeler.", "ru": "Несколько кадров изнутри Peony — кабинеты, небольшие ритуалы и тихие уголки между ними.", "zh": "Peony 内部的一些片刻——理疗室、细小的仪式，以及其间安静的角落。", "hi": "Peony के भीतर के कुछ पल — उपचार कक्ष, छोटे अनुष्ठान, और बीच के शांत कोने।"}'::jsonb),
  ('gallery.title', '{"th": "พื้นที่ รายละเอียด และความสงบ", "en": "The space, the details, the calm", "tr": "Mekân, detaylar ve sükûnet", "ru": "Пространство, детали и тишина", "zh": "空间、细节与静谧", "hi": "जगह, बारीकियाँ और ठहराव"}'::jsonb),
  ('gallery.treatments', '{"th": "การบำบัด", "en": "Treatments", "tr": "Uygulamalar", "ru": "Процедуры", "zh": "理疗", "hi": "उपचार"}'::jsonb),
  ('hero.cta1', '{"th": "จองคิว", "en": "Book Appointment", "tr": "Randevu Al", "ru": "Записаться", "zh": "立即预约", "hi": "अपॉइंटमेंट लें"}'::jsonb),
  ('hero.cta2', '{"th": "ดูบริการทั้งหมด", "en": "Explore Treatments", "tr": "Uygulamaları Gör", "ru": "Смотреть процедуры", "zh": "浏览项目", "hi": "उपचार देखें"}'::jsonb),
  ('hero.eyebrow', '{"th": "นวดแผนไทย &amp; สปา", "en": "Thai Massage &amp; Spa", "tr": "Tayland Masajı &amp; Spa", "ru": "Тайский массаж &amp; спа", "zh": "泰式按摩 &amp; SPA", "hi": "थाई मसाज &amp; स्पा"}'::jsonb),
  ('hero.scroll', '{"th": "เลื่อนลง", "en": "Scroll", "tr": "Kaydır", "ru": "Вниз", "zh": "向下", "hi": "नीचे"}'::jsonb),
  ('hero.text', '{"th": "ที่พักใจอันเงียบสงบ ที่ซึ่งศาสตร์การนวดแผนไทยดั้งเดิมมาบรรจบกับน้ำมันอุ่น ลูกประคบสมุนไพร และการดูแลอย่างไม่เร่งรีบ เพื่อให้กายและใจของคุณกลับมาสงบอีกครั้ง", "en": "A quiet retreat where traditional Thai technique meets warm oils, herbal compresses and unhurried attention — so your body and mind can settle again.", "tr": "Geleneksel Tayland tekniğinin sıcak yağlar, bitkisel kompresler ve acelesiz bir ilgiyle buluştuğu sessiz bir sığınak — bedeniniz ve zihniniz yeniden yerine otursun diye.", "ru": "Тихое убежище, где традиционная тайская техника соединяется с тёплыми маслами, травяными компрессами и неторопливым вниманием — чтобы тело и мысли снова пришли в равновесие.", "zh": "一处安静的栖息地，传统泰式手法在这里遇见温热精油、草药热敷包与不被催促的专注照护——让身体与心绪重新安顿下来。", "hi": "एक शांत ठिकाना, जहाँ पारंपरिक थाई तकनीक गर्म तेलों, हर्बल कंप्रेस और बिना जल्दबाज़ी वाले ध्यान से मिलती है — ताकि आपका शरीर और मन फिर से ठहर सकें।"}'::jsonb),
  ('hero.title', '{"th": "นวดแผนไทยดั้งเดิม ที่ Peony", "en": "Traditional Thai Massage at Peony", "tr": "Peony ile Geleneksel Tayland Masajı", "ru": "Традиционный тайский массаж в Peony", "zh": "在 Peony 体验传统泰式按摩", "hi": "Peony में पारंपरिक थाई मसाज"}'::jsonb),
  ('meta.description', '{"th": "นวดแผนไทยดั้งเดิม พิธีกรรมน้ำมันหอมระเหย และการดูแลอย่างสงบ ไม่เร่งรีบ", "en": "Traditional Thai therapies, aromatic oil rituals and quiet, unhurried care.", "tr": "Geleneksel Tayland terapileri, aromatik yağ ritüelleri ve sessiz, aceleye getirilmeyen bir bakım.", "ru": "Традиционные тайские техники, ритуалы с ароматическими маслами и спокойный, неторопливый уход.", "zh": "传统泰式手法、芳香精油仪式，以及安静从容、不被催促的照护。", "hi": "पारंपरिक थाई तकनीक, सुगंधित तेल के अनुष्ठान और शांत, बिना जल्दबाज़ी वाली देखभाल।"}'::jsonb),
  ('meta.title', '{"th": "Peony Thai Massage & Spa", "en": "Peony Thai Massage & Spa", "tr": "Peony Thai Massage & Spa", "ru": "Peony Thai Massage & Spa", "zh": "Peony Thai Massage & Spa", "hi": "Peony Thai Massage & Spa"}'::jsonb),
  ('nav.about', '{"th": "เกี่ยวกับเรา", "en": "About", "tr": "Hakkımızda", "ru": "О нас", "zh": "关于我们", "hi": "हमारे बारे में"}'::jsonb),
  ('nav.book', '{"th": "จองคิว", "en": "Book Appointment", "tr": "Randevu Al", "ru": "Записаться", "zh": "预约", "hi": "अपॉइंटमेंट लें"}'::jsonb),
  ('nav.contact', '{"th": "ติดต่อเรา", "en": "Contact", "tr": "İletişim", "ru": "Контакты", "zh": "联系我们", "hi": "संपर्क"}'::jsonb),
  ('nav.faq', '{"th": "คำถามที่พบบ่อย", "en": "FAQ", "tr": "S.S.S.", "ru": "Вопросы", "zh": "常见问题", "hi": "सामान्य प्रश्न"}'::jsonb),
  ('nav.gallery', '{"th": "แกลเลอรี", "en": "Gallery", "tr": "Galeri", "ru": "Галерея", "zh": "环境相册", "hi": "गैलरी"}'::jsonb),
  ('nav.plans', '{"th": "แพ็กเกจ", "en": "Packages", "tr": "Paketler", "ru": "Пакеты", "zh": "套餐", "hi": "पैकेज"}'::jsonb),
  ('nav.services', '{"th": "บริการนวด", "en": "Treatments", "tr": "Uygulamalar", "ru": "Процедуры", "zh": "理疗项目", "hi": "उपचार"}'::jsonb),
  ('plans.badge', '{"th": "ได้รับความนิยมที่สุด", "en": "Most chosen", "tr": "En çok tercih edilen", "ru": "Выбирают чаще всего", "zh": "最多人选择", "hi": "सबसे ज़्यादा चुना गया"}'::jsonb),
  ('plans.cta', '{"th": "เลือกแพ็กเกจนี้", "en": "Book this", "tr": "Bunu seç", "ru": "Выбрать", "zh": "选择此套餐", "hi": "यह चुनें"}'::jsonb),
  ('plans.eyebrow', '{"th": "แพ็กเกจ", "en": "Packages", "tr": "Paketler", "ru": "Пакеты", "zh": "套餐", "hi": "पैकेज"}'::jsonb),
  ('plans.text', '{"th": "สามวิธีในการใช้เวลากับเรา ไม่มีการขายเพิ่มที่เคาน์เตอร์ ไม่มีอะไรเซอร์ไพรส์", "en": "Three ways to spend your time with us. No add-ons at the counter, no surprises.", "tr": "Bizimle vakit geçirmenin üç yolu. Kasada ek satış yok, sürpriz yok.", "ru": "Три способа провести время у нас. Никаких допродаж на ресепшене и никаких сюрпризов.", "zh": "三种与我们共度时光的方式。前台不做额外推销，也没有意外收费。", "hi": "हमारे साथ समय बिताने के तीन तरीक़े। काउंटर पर कोई अतिरिक्त बिक्री नहीं, कोई हैरानी नहीं।"}'::jsonb),
  ('plans.title', '{"th": "ราคาเรียบง่าย ตรงไปตรงมา", "en": "Simple, honest pricing", "tr": "Sade ve dürüst fiyatlandırma", "ru": "Простые и честные цены", "zh": "价格简单、透明", "hi": "सरल और साफ़ कीमतें"}'::jsonb),
  ('quotes.eyebrow', '{"th": "เสียงจากลูกค้า", "en": "Guest Notes", "tr": "Misafir Notları", "ru": "Отзывы гостей", "zh": "客人留言", "hi": "मेहमानों के शब्द"}'::jsonb),
  ('quotes.title', '{"th": "สิ่งที่ลูกค้าพูดหลังออกจากห้อง", "en": "What people say afterwards", "tr": "Sonrasında söyledikleri", "ru": "Что говорят после сеанса", "zh": "结束之后，他们这样说", "hi": "बाद में लोग क्या कहते हैं"}'::jsonb),
  ('services.eyebrow', '{"th": "บริการนวด", "en": "Treatments", "tr": "Uygulamalar", "ru": "Процедуры", "zh": "理疗项目", "hi": "उपचार"}'::jsonb),
  ('services.text', '{"th": "ทุกบริการเริ่มต้นด้วยการพูดคุยสั้น ๆ เพื่อให้แรงกด น้ำมัน และจังหวะ เหมาะกับตัวคุณ ไม่ใช่เหมาะกับรายการในเมนู", "en": "Every treatment begins with a short conversation, so the pressure, oils and pace are matched to you rather than to a menu.", "tr": "Her uygulama kısa bir sohbetle başlar; böylece basınç, yağ ve tempo bir menüye değil size göre ayarlanır.", "ru": "Каждая процедура начинается с короткого разговора — чтобы давление, масла и темп подбирались под вас, а не под пункт меню.", "zh": "每次理疗都从简短沟通开始，让力度、精油与节奏贴合你本人，而不是贴合菜单上的某一行。", "hi": "हर उपचार एक छोटी बातचीत से शुरू होता है, ताकि दबाव, तेल और गति किसी मेन्यू के नहीं, आपके अनुसार तय हों।"}'::jsonb),
  ('services.title', '{"th": "เลือกตามความรู้สึกของคุณในวันนี้", "en": "Chosen for how you feel today", "tr": "Bugün nasıl hissettiğinize göre seçilir", "ru": "Выбирается по вашему сегодняшнему состоянию", "zh": "按你今天的状态来挑选", "hi": "आज आप कैसा महसूस कर रहे हैं, उसी के अनुसार"}'::jsonb)
on conflict (key) do update set value = excluded.value;

insert into peony_services (slug, position, image_url, name, description) values
  ('thai', 0, 'assets/art/svc-thai.svg', '{"th": "นวดแผนไทยดั้งเดิม", "en": "Traditional Thai Massage", "tr": "Geleneksel Tayland Masajı", "ru": "Традиционный тайский массаж", "zh": "传统泰式按摩", "hi": "पारंपरिक थाई मसाज"}'::jsonb, '{"th": "นวดแบบไม่ใช้น้ำมันบนเบาะ พร้อมการยืดเหยียดและแรงกดเป็นจังหวะตามแนวเส้นพลังงานของร่างกาย", "en": "Dry massage on a mat with guided stretching and rhythmic pressure along the body''s energy lines.", "tr": "Minder üzerinde, eşlikli esnetmeler ve vücudun enerji hatları boyunca ritmik basınçla uygulanan kuru masaj.", "ru": "Сухой массаж на мате с мягкими растяжками и ритмичным давлением вдоль энергетических линий тела.", "zh": "在垫上进行的无油按摩，配合引导式伸展，沿身体能量线施以有节奏的按压。", "hi": "गद्दे पर बिना तेल की मसाज, जिसमें शरीर की ऊर्जा रेखाओं पर लयबद्ध दबाव और सहायक स्ट्रेचिंग होती है।"}'::jsonb),
  ('oil', 1, 'assets/art/svc-oil.svg', '{"th": "นวดน้ำมันสไตล์ไทย", "en": "Thai Oil Massage", "tr": "Tayland Yağ Masajı", "ru": "Тайский массаж с маслом", "zh": "泰式精油按摩", "hi": "थाई ऑइल मसाज"}'::jsonb, '{"th": "การลูบไล้ยาวต่อเนื่องด้วยน้ำมันอุ่น ช่วยคลายกล้ามเนื้อที่ตึงและทำให้จิตใจที่ว้าวุ่นสงบลง", "en": "Long, flowing strokes with warm oil to soften tight muscle and quiet a restless mind.", "tr": "Sıcak yağla uzun, akıcı hareketler; gergin kası yumuşatır, huzursuz zihni susturur.", "ru": "Длинные плавные движения с тёплым маслом: расслабляют зажатые мышцы и успокаивают беспокойные мысли.", "zh": "以温热精油进行绵长流畅的推抚，舒缓紧绷的肌肉，也让浮躁的思绪静下来。", "hi": "गर्म तेल के साथ लंबे, बहते स्ट्रोक — कसी हुई मांसपेशियों को ढीला करते हैं और बेचैन मन को शांत।"}'::jsonb),
  ('aroma', 2, 'assets/art/svc-aroma.svg', '{"th": "นวดอโรมาเธอราพี", "en": "Aromatherapy Massage", "tr": "Aroma Terapi Masajı", "ru": "Ароматерапевтический массаж", "zh": "芳香疗法按摩", "hi": "अरोमाथेरेपी मसाज"}'::jsonb, '{"th": "การนวดอย่างนุ่มนวลด้วยน้ำมันหอมระเหยที่เลือกให้เหมาะกับคุณ — ผ่อนคลาย กระปรี้กระเปร่า หรือปรับสมดุล", "en": "Gentle bodywork with an essential-oil blend chosen for you — calming, reviving or balancing.", "tr": "Size özel seçilen uçucu yağ karışımıyla nazik bir çalışma — sakinleştirici, canlandırıcı ya da dengeleyici.", "ru": "Мягкая работа с телом и смесью эфирных масел, подобранной для вас — успокаивающей, бодрящей или балансирующей.", "zh": "以为你调配的精油进行轻柔的身体照护——安神、提振或平衡，由你的状态决定。", "hi": "आपके लिए चुने गए एसेंशियल ऑइल मिश्रण के साथ कोमल बॉडीवर्क — शांत करने वाला, स्फूर्ति देने वाला या संतुलन बनाने वाला।"}'::jsonb),
  ('foot', 3, 'assets/art/svc-foot.svg', '{"th": "นวดกดจุดฝ่าเท้า", "en": "Foot Reflexology", "tr": "Ayak Refleksolojisi", "ru": "Рефлексология стоп", "zh": "足部反射疗法", "hi": "फुट रिफ्लेक्सोलॉजी"}'::jsonb, '{"th": "แรงกดเฉพาะจุดสะท้อนบริเวณฝ่าเท้าและน่อง ให้ความรู้สึกมั่นคงและผ่อนคลายอย่างลึกซึ้ง", "en": "Focused pressure on the reflex points of the feet and lower legs. Deeply grounding.", "tr": "Ayak ve alt bacaktaki refleks noktalarına odaklı basınç. Derinden yere basma hissi verir.", "ru": "Точечное давление на рефлекторные зоны стоп и голеней. Глубоко заземляет и снимает усталость.", "zh": "针对足底与小腿反射区的定点按压，让人由内而外地踏实放松。", "hi": "पैरों और पिंडलियों के रिफ्लेक्स बिंदुओं पर केंद्रित दबाव। गहराई तक स्थिर और हल्का महसूस कराता है।"}'::jsonb),
  ('back', 4, 'assets/art/svc-back.svg', '{"th": "นวดหลัง คอ &amp; บ่า", "en": "Back, Neck & Shoulders", "tr": "Sırt, Boyun &amp; Omuz", "ru": "Спина, шея &amp; плечи", "zh": "背颈肩理疗", "hi": "पीठ, गर्दन &amp; कंधे"}'::jsonb, '{"th": "คอร์สสั้นที่เจาะจงความตึงซึ่งสะสมจากการนั่งโต๊ะ จ้องหน้าจอ และการเดินทางไกล", "en": "A short, targeted session for the tension that builds from desks, screens and long drives.", "tr": "Masa başı, ekran ve uzun yol yüzünden biriken gerginlik için kısa ve hedefli bir seans.", "ru": "Короткий целевой сеанс для напряжения, которое копится от работы за столом, экранов и долгой дороги.", "zh": "针对久坐办公、长时间看屏幕与长途驾驶所累积的紧绷，进行短时精准的处理。", "hi": "डेस्क, स्क्रीन और लंबी ड्राइव से जमा हुए तनाव के लिए छोटा, लक्षित सत्र।"}'::jsonb),
  ('herbal', 5, 'assets/art/svc-herbal.svg', '{"th": "ประคบสมุนไพร", "en": "Herbal Compress", "tr": "Bitkisel Kompres", "ru": "Травяной компресс", "zh": "泰式草药热敷", "hi": "हर्बल कंप्रेस"}'::jsonb, '{"th": "ลูกประคบสมุนไพรไทยนึ่งร้อน กดลงบนกล้ามเนื้อ — อบอุ่น หอม และช้า ๆ", "en": "Steamed pouches of Thai herbs pressed into the muscle — warm, aromatic and slow.", "tr": "Buharda ısıtılmış Tayland bitki keseleri kasa bastırılır — sıcak, aromatik ve yavaş.", "ru": "Распаренные мешочки с тайскими травами прижимаются к мышцам — тепло, ароматно и медленно.", "zh": "蒸热的泰式草药包按压于肌肉之上——温热、芳香，节奏缓慢。", "hi": "भाप में गरम की गई थाई जड़ी-बूटियों की पोटलियाँ मांसपेशियों पर दबाई जाती हैं — गर्म, सुगंधित और धीमी।"}'::jsonb),
  ('scrub', 6, 'assets/art/svc-scrub.svg', '{"th": "ขัดผิวและบำรุงผิวกาย", "en": "Body Scrub & Polish", "tr": "Vücut Peelingi", "ru": "Скраб и полировка тела", "zh": "全身去角质护理", "hi": "बॉडी स्क्रब &amp; पॉलिश"}'::jsonb, '{"th": "สครับจากแร่ธาตุและสมุนไพร ช่วยผลัดผิวหมองคล้ำ ให้ผิวเรียบเนียนและนุ่มชุ่มชื้น", "en": "A mineral and botanical scrub that lifts dull skin and leaves it smooth and soft.", "tr": "Mineral ve bitkisel peeling; matlaşmış cildi arındırır, pürüzsüz ve yumuşak bırakır.", "ru": "Минерально-растительный скраб снимает тусклый слой кожи и оставляет её гладкой и мягкой.", "zh": "矿物与植萃磨砂，温和带走暗沉角质，留下平滑柔软的肤感。", "hi": "खनिज और वनस्पति स्क्रब, जो निस्तेज त्वचा हटाकर उसे चिकना और मुलायम छोड़ता है।"}'::jsonb),
  ('facial', 7, 'assets/art/svc-facial.svg', '{"th": "ทรีตเมนต์บำรุงผิวหน้า", "en": "Facial Ritual", "tr": "Yüz Bakım Ritüeli", "ru": "Ритуал для лица", "zh": "面部护理仪式", "hi": "फेशियल रिचुअल"}'::jsonb, '{"th": "ทำความสะอาด นวดหน้าอย่างนุ่มนวล และมาสก์บำรุง ปิดท้ายด้วยผ้าประคบสมุนไพรเย็น", "en": "Cleansing, gentle massage and a nourishing mask, finished with a cool herbal compress.", "tr": "Temizlik, nazik masaj ve besleyici bir maske; serin bitkisel kompresle tamamlanır.", "ru": "Очищение, мягкий массаж и питательная маска, в завершение — прохладный травяной компресс.", "zh": "清洁、轻柔按摩与滋养面膜，最后以清凉草药敷布收尾。", "hi": "सफ़ाई, कोमल मसाज और पोषक मास्क, अंत में ठंडे हर्बल कंप्रेस के साथ।"}'::jsonb)
on conflict (slug) do update set position=excluded.position, image_url=excluded.image_url, name=excluded.name, description=excluded.description;

insert into peony_plans (position, featured, name, note, items) values
  (0, false, '{"th": "Essential", "en": "Essential", "tr": "Temel", "ru": "Essential", "zh": "Essential", "hi": "Essential"}'::jsonb, '{"th": "การรีเซ็ตสั้น ๆ สำหรับวันที่เวลามีน้อย แต่ความตึงเครียดมีมาก", "en": "A short reset when time is tight but tension is not.", "tr": "Zamanın kısıtlı, gerginliğin bol olduğu günler için kısa bir sıfırlama.", "ru": "Короткая перезагрузка, когда времени мало, а напряжения — много.", "zh": "时间紧、压力却不小的日子里，一次简短的重启。", "hi": "उन दिनों के लिए छोटा रीसेट, जब समय कम हो पर तनाव कम न हो।"}'::jsonb, '{"th": ["เน้นหลัง คอ และบ่า", "ปิดท้ายด้วยผ้าขนหนูอุ่น", "ชาสมุนไพรหลังนวด", "นักบำบัดหนึ่งท่าน"], "en": ["Back, neck & shoulder focus", "Warm towel finish", "Herbal tea afterwards", "Single therapist"], "tr": ["Sırt, boyun ve omuz odaklı", "Sıcak havlu bitişi", "Sonrasında bitki çayı", "Tek terapist"], "ru": ["Акцент на спине, шее и плечах", "Завершение тёплым полотенцем", "Травяной чай после сеанса", "Один мастер"], "zh": ["聚焦背、颈与肩", "温热毛巾收尾", "理疗后草本茶", "单人理疗师"], "hi": ["पीठ, गर्दन और कंधों पर ध्यान", "गर्म तौलिए के साथ समापन", "बाद में हर्बल चाय", "एक थेरेपिस्ट"]}'::jsonb),
  (1, true, '{"th": "Signature", "en": "Signature", "tr": "İmza", "ru": "Signature", "zh": "Signature", "hi": "Signature"}'::jsonb, '{"th": "ทรีตเมนต์เต็มตัวประจำร้าน — คอร์สที่ลูกค้ากลับมาใช้บริการซ้ำมากที่สุด", "en": "Our full-body ritual — the one most guests come back for.", "tr": "Tüm vücut ritüelimiz — misafirlerin en çok geri döndüğü seçenek.", "ru": "Наш ритуал для всего тела — именно за ним гости возвращаются чаще всего.", "zh": "我们的全身理疗仪式——回头客最常选择的一项。", "hi": "हमारा पूरे शरीर का अनुष्ठान — जिसके लिए मेहमान सबसे ज़्यादा लौटते हैं।"}'::jsonb, '{"th": ["นวดแผนไทยหรือนวดน้ำมันเต็มตัว", "เลือกน้ำมันอโรมาได้เอง", "ปิดท้ายด้วยนวดกดจุดฝ่าเท้า", "เพิ่มลูกประคบสมุนไพรได้ตามต้องการ", "ชาสมุนไพรหลังนวด"], "en": ["Full body Thai or oil massage", "Aromatherapy oil of your choice", "Foot reflexology finish", "Herbal compress on request", "Herbal tea afterwards"], "tr": ["Tüm vücut Tayland ya da yağ masajı", "Seçtiğiniz aroma terapi yağı", "Ayak refleksolojisi bitişi", "İstenirse bitkisel kompres", "Sonrasında bitki çayı"], "ru": ["Тайский или масляный массаж всего тела", "Аромамасло на ваш выбор", "Завершение рефлексологией стоп", "Травяной компресс по желанию", "Травяной чай после сеанса"], "zh": ["全身泰式或精油按摩", "自选芳疗精油", "足部反射疗法收尾", "可按需加草药热敷", "理疗后草本茶"], "hi": ["पूरे शरीर की थाई या ऑइल मसाज", "अपनी पसंद का अरोमा ऑइल", "फुट रिफ्लेक्सोलॉजी के साथ समापन", "अनुरोध पर हर्बल कंप्रेस", "बाद में हर्बल चाय"]}'::jsonb),
  (2, false, '{"th": "Retreat", "en": "Retreat", "tr": "İnziva", "ru": "Retreat", "zh": "Retreat", "hi": "Retreat"}'::jsonb, '{"th": "ครึ่งวันอันไม่เร่งรีบ สำหรับวันที่คุณอยากหายไปจากทุกสิ่งสักพัก", "en": "An unhurried half-day for when you want to disappear for a while.", "tr": "Bir süreliğine kaybolmak istediğiniz, acelesiz bir yarım gün.", "ru": "Неторопливые полдня для тех, кто хочет ненадолго исчезнуть.", "zh": "想暂时从一切中消失时，一个不赶时间的半天。", "hi": "एक बिना जल्दबाज़ी वाला आधा दिन, जब आप कुछ देर के लिए ग़ायब हो जाना चाहें।"}'::jsonb, '{"th": ["นวดเต็มตัว", "ขัดผิวและบำรุงผิวกาย", "ทรีตเมนต์บำรุงผิวหน้า", "นวดกดจุดฝ่าเท้า", "ห้องส่วนตัว", "รวมเครื่องดื่มและของว่าง"], "en": ["Full body massage", "Body scrub & polish", "Facial ritual", "Foot reflexology", "Private room", "Refreshments included"], "tr": ["Tüm vücut masajı", "Vücut peelingi", "Yüz bakım ritüeli", "Ayak refleksolojisi", "Özel oda", "İkramlar dâhil"], "ru": ["Массаж всего тела", "Скраб и полировка тела", "Ритуал для лица", "Рефлексология стоп", "Отдельный кабинет", "Напитки и угощение включены"], "zh": ["全身按摩", "全身去角质护理", "面部护理仪式", "足部反射疗法", "独立房间", "含茶点招待"], "hi": ["पूरे शरीर की मसाज", "बॉडी स्क्रब और पॉलिश", "फेशियल रिचुअल", "फुट रिफ्लेक्सोलॉजी", "निजी कमरा", "जलपान शामिल"]}'::jsonb);

insert into peony_faqs (position, question, answer) values
  (0, '{"th": "ต้องจองล่วงหน้าหรือไม่?", "en": "Do I need to book in advance?", "tr": "Önceden randevu almam gerekiyor mu?", "ru": "Нужно ли записываться заранее?", "zh": "需要提前预约吗？", "hi": "क्या पहले से बुकिंग ज़रूरी है?"}'::jsonb, '{"th": "เราแนะนำให้จองล่วงหน้า โดยเฉพาะช่วงเย็นและวันหยุดสุดสัปดาห์ ลูกค้า walk-in ยินดีต้อนรับเสมอเมื่อมีนักบำบัดว่าง แต่การจองจะช่วยยืนยันห้องและเวลาที่คุณต้องการ", "en": "We recommend it, especially in the evenings and at weekends. Walk-ins are welcome whenever a therapist is free, but booking guarantees the room and the time you want.", "tr": "Özellikle akşam saatleri ve hafta sonları için öneririz. Terapist müsait olduğunda randevusuz da kabul ediyoruz, ancak randevu istediğiniz odayı ve saati garantiler.", "ru": "Рекомендуем, особенно на вечерние часы и выходные. Без записи мы тоже принимаем, когда мастер свободен, но запись гарантирует нужный вам кабинет и время.", "zh": "建议提前预约，尤其是傍晚时段与周末。理疗师有空档时也欢迎直接到店，但预约能确保你想要的房间与时间。", "hi": "हम सलाह देते हैं, ख़ासकर शाम और सप्ताहांत के लिए। थेरेपिस्ट खाली होने पर बिना बुकिंग भी स्वागत है, पर बुकिंग से आपका मनचाहा कमरा और समय तय हो जाता है।"}'::jsonb),
  (1, '{"th": "ควรแต่งกายอย่างไร?", "en": "What should I wear?", "tr": "Ne giymeliyim?", "ru": "Что надеть?", "zh": "该穿什么？", "hi": "क्या पहनकर आएँ?"}'::jsonb, '{"th": "สำหรับนวดแผนไทยดั้งเดิม เรามีชุดผ้าฝ้ายหลวมสบายให้เปลี่ยน ส่วนทรีตเมนต์น้ำมัน คุณถอดเสื้อผ้าได้เท่าที่รู้สึกสบายใจ และจะมีผ้าคลุมให้ตลอดการนวด", "en": "For traditional Thai massage we provide loose cotton clothing you change into. For oil treatments you undress to your comfort level and are covered with towels throughout.", "tr": "Geleneksel Tayland masajı için üzerinizi değiştireceğiniz bol pamuklu kıyafet veriyoruz. Yağlı uygulamalarda rahat ettiğiniz kadar soyunursunuz ve seans boyunca havluyla örtülü kalırsınız.", "ru": "Для традиционного тайского массажа мы выдаём свободную хлопковую одежду для переодевания. Для процедур с маслом вы раздеваетесь настолько, насколько вам комфортно, и всё время остаётесь укрыты полотенцами.", "zh": "传统泰式按摩我们会提供宽松棉质服装供你更换。精油类项目则可依自己觉得舒适的程度着装，全程都会以浴巾覆盖。", "hi": "पारंपरिक थाई मसाज के लिए हम ढीले सूती कपड़े देते हैं, जिन्हें आप बदल लेते हैं। तेल वाले उपचारों में आप अपनी सहजता के अनुसार कपड़े उतारते हैं और पूरे समय तौलिए से ढके रहते हैं।"}'::jsonb),
  (2, '{"th": "ควรมาถึงก่อนเวลานานแค่ไหน?", "en": "How early should I arrive?", "tr": "Ne kadar erken gelmeliyim?", "ru": "За сколько приходить?", "zh": "应该提前多久到？", "hi": "कितनी जल्दी पहुँचना चाहिए?"}'::jsonb, '{"th": "มาก่อนเวลานัดสักสิบนาทีก็เพียงพอ จะได้มีเวลาเปลี่ยนชุด จิบชาสักถ้วย และบอกนักบำบัดว่าวันนี้ร่างกายคุณต้องการอะไร", "en": "Ten minutes before your appointment is plenty. It gives you time to change, have a cup of tea, and tell your therapist what your body needs today.", "tr": "Randevunuzdan on dakika önce yeterli. Üzerinizi değiştirmeye, bir fincan çay içmeye ve terapistinize bugün bedeninizin neye ihtiyacı olduğunu anlatmaya vakit kalır.", "ru": "Десяти минут до начала вполне достаточно. Успеете переодеться, выпить чашку чая и рассказать мастеру, что вашему телу нужно сегодня.", "zh": "提前十分钟就足够了。足以更衣、喝杯茶，并告诉理疗师你的身体今天需要什么。", "hi": "अपॉइंटमेंट से दस मिनट पहले पर्याप्त है। इतने में आप कपड़े बदल सकते हैं, एक कप चाय पी सकते हैं और थेरेपिस्ट को बता सकते हैं कि आज आपके शरीर को क्या चाहिए।"}'::jsonb),
  (3, '{"th": "เหมาะกับผู้ที่มาครั้งแรกหรือไม่?", "en": "Is it suitable for a first-time guest?", "tr": "İlk kez gelen biri için uygun mu?", "ru": "Подойдёт ли новичку?", "zh": "第一次来合适吗？", "hi": "क्या यह पहली बार आने वालों के लिए ठीक है?"}'::jsonb, '{"th": "เหมาะอย่างยิ่ง เพียงบอกเราว่าเป็นครั้งแรก นักบำบัดจะเริ่มอย่างนุ่มนวล อธิบายทุกขั้นตอน และปรับน้ำหนักมือไปตลอด ไม่ควรมีจังหวะไหนที่ทำให้เจ็บ", "en": "Very much so. Tell us it is your first visit and your therapist will start gently, explain each stage and adjust the pressure as you go. Nothing should ever hurt.", "tr": "Fazlasıyla. İlk ziyaretiniz olduğunu söyleyin; terapistiniz nazik başlar, her aşamayı anlatır ve ilerledikçe basıncı ayarlar. Hiçbir aşamada canınız yanmamalı.", "ru": "Вполне. Скажите, что вы у нас впервые — мастер начнёт мягко, объяснит каждый этап и будет корректировать давление по ходу. Больно быть не должно ни на одном этапе.", "zh": "非常合适。告诉我们是初次到访，理疗师会从轻缓开始，逐步说明每个阶段，并随时调整力度。任何环节都不该让你感到疼痛。", "hi": "बिल्कुल। बता दीजिए कि यह आपकी पहली बार है — थेरेपिस्ट धीरे शुरू करेंगे, हर चरण समझाएँगे और साथ-साथ दबाव समायोजित करेंगे। कहीं भी दर्द नहीं होना चाहिए।"}'::jsonb),
  (4, '{"th": "เลือกน้ำหนักมือเองได้ไหม?", "en": "Can I choose the pressure?", "tr": "Basıncı ben seçebilir miyim?", "ru": "Можно ли выбрать силу нажима?", "zh": "力度可以自己选吗？", "hi": "क्या मैं दबाव चुन सकता/सकती हूँ?"}'::jsonb, '{"th": "ได้เสมอ เบา กลาง หรือหนัก และเปลี่ยนใจกลางคันก็ได้ เพียงบอกเรา นักบำบัดยินดีปรับให้มากกว่าปล่อยให้คุณฝืนทน", "en": "Always. Light, medium or firm — and you can change your mind halfway through. Just say the word; your therapist would far rather adjust than have you endure.", "tr": "Her zaman. Hafif, orta ya da sert — üstelik seansın ortasında fikrinizi değiştirebilirsiniz. Söylemeniz yeterli; terapistiniz sizin katlanmanızdansa ayar yapmayı çok daha çok ister.", "ru": "Всегда. Лёгкий, средний или сильный — и передумать можно прямо посреди сеанса. Просто скажите: мастеру гораздо важнее подстроиться, чем видеть, как вы терпите.", "zh": "随时可以。轻、中或重都行，中途改主意也没问题。开口说一声即可——比起让你忍着，理疗师更希望及时调整。", "hi": "हमेशा। हल्का, मध्यम या तेज़ — और बीच में मन भी बदल सकते हैं। बस कह दीजिए; थेरेपिस्ट आपको सहते देखने के बजाय समायोजन करना कहीं ज़्यादा पसंद करेंगे।"}'::jsonb),
  (5, '{"th": "นโยบายการยกเลิกเป็นอย่างไร?", "en": "What is your cancellation policy?", "tr": "İptal koşullarınız nedir?", "ru": "Каковы условия отмены?", "zh": "取消政策是怎样的？", "hi": "रद्द करने की नीति क्या है?"}'::jsonb, '{"th": "แจ้งล่วงหน้าอย่างน้อยสองสามชั่วโมง ไม่มีค่าใช้จ่ายใด ๆ เรื่องไม่คาดคิดเกิดขึ้นได้เสมอ เราเพียงอยากเปิดคิวให้ลูกค้าท่านอื่นมากกว่าปล่อยห้องว่างไว้เฉย ๆ", "en": "Let us know at least a few hours ahead and there is no charge at all. Life happens; we would simply rather offer the slot to someone else than leave the room empty.", "tr": "En az birkaç saat önceden haber verin, hiçbir ücret alınmaz. Hayat işte; odayı boş bırakmaktansa saati başka birine açmayı tercih ederiz.", "ru": "Предупредите хотя бы за несколько часов — никакой платы не будет. Всякое случается; нам просто важнее отдать это время другому гостю, чем оставить кабинет пустым.", "zh": "至少提前几小时告知，我们不收取任何费用。生活总有变化；与其让房间空着，我们更愿意把这个时段留给其他客人。", "hi": "कम से कम कुछ घंटे पहले बता दीजिए, कोई शुल्क नहीं लगेगा। ज़िंदगी में सब कुछ होता है; हम कमरा खाली रखने के बजाय वह समय किसी और को देना पसंद करेंगे।"}'::jsonb);

insert into peony_testimonials (position, author, role, body) values
  (0, '-doldurulacak-', '-doldurulacak-', '{"th": "ฉันเดินเข้ามาพร้อมงานที่ค้างมาทั้งสัปดาห์ และเดินออกไปโดยไม่มีมันติดตัว นักบำบัดอ่านความตึงที่บ่าของฉันออกก่อนที่ฉันจะเอ่ยปากเสียอีก", "en": "I walked in carrying a week of deadlines and walked out without them. The therapist read the tension in my shoulders before I said a word.", "tr": "İçeri bir haftalık teslim tarihiyle girdim, onlarsız çıktım. Terapist ben tek kelime etmeden omzumdaki gerginliği okudu.", "ru": "Я пришла с грузом недельных дедлайнов, а вышла уже без него. Мастер прочитал напряжение в моих плечах раньше, чем я успела сказать хоть слово.", "zh": "我带着一整周的工作压力走进来，走出去时它已经不在身上了。我还没开口，理疗师就读出了我肩上的紧绷。", "hi": "मैं पूरे हफ़्ते की डेडलाइनें लेकर अंदर आई और उनके बिना बाहर निकली। मेरे कुछ कहने से पहले ही थेरेपिस्ट ने मेरे कंधों का तनाव पढ़ लिया।"}'::jsonb),
  (1, '-doldurulacak-', '-doldurulacak-', '{"th": "เป็นชั่วโมงที่เงียบที่สุดในรอบหลายเดือน ไม่มีอะไรเร่งรีบ ไม่มีการขายเพิ่ม มีเพียงฝีมือที่ดีจริง และห้องที่ทำให้เราปิดสวิตช์ตัวเองได้", "en": "The quietest hour I have had in months. Nothing rushed, nothing upsold — just genuinely skilled hands and a room that lets you switch off.", "tr": "Aylardır geçirdiğim en sessiz saatti. Ne acele vardı ne de ek satış çabası — sadece gerçekten usta eller ve insanı kapatan bir oda.", "ru": "Самый тихий час за последние месяцы. Никакой спешки, никаких попыток что-то допродать — просто по-настоящему умелые руки и кабинет, в котором получается выключиться.", "zh": "这是我几个月来最安静的一小时。没有催促，也没有推销，只有真正到位的手法，和一个能让人彻底关机的房间。", "hi": "महीनों में मेरा सबसे शांत घंटा। न कोई जल्दबाज़ी, न कुछ अतिरिक्त बेचने की कोशिश — बस सचमुच कुशल हाथ और एक ऐसा कमरा जो आपको बंद हो जाने देता है।"}'::jsonb),
  (2, '-doldurulacak-', '-doldurulacak-', '{"th": "ฉันนวดแผนไทยมาเยอะมากตลอดหลายปี ที่นี่คือของจริง เทคนิคถูกต้อง น้ำหนักมือพอดี และนักบำบัดที่รับฟังจริง ๆ", "en": "I have had a lot of Thai massage over the years. This is the real thing: proper technique, proper pressure, and a therapist who actually listens.", "tr": "Yıllar içinde çok Tayland masajı yaptırdım. Bu gerçek olanı: doğru teknik, doğru basınç ve gerçekten dinleyen bir terapist.", "ru": "За годы я перепробовал много тайского массажа. Здесь всё настоящее: верная техника, верное давление и мастер, который действительно слушает.", "zh": "这些年我做过很多泰式按摩。这里是货真价实的：手法对、力度对，理疗师也是真的在听你说话。", "hi": "इन वर्षों में मैंने बहुत थाई मसाज करवाई है। यह असली वाली है: सही तकनीक, सही दबाव, और एक थेरेपिस्ट जो वाकई सुनता है।"}'::jsonb);

insert into peony_gallery (position, image_url, category) values
  (0, 'media/gallery-01.jpg?v=1', 'space'),
  (1, 'media/gallery-02.jpg?v=1', 'space'),
  (2, 'media/gallery-03.jpg?v=1', 'details'),
  (3, 'media/gallery-04.jpg?v=1', 'details'),
  (4, 'media/gallery-05.jpg?v=1', 'details'),
  (5, 'media/gallery-06.jpg?v=1', 'details'),
  (6, 'media/gallery-07.jpg?v=1', 'details'),
  (7, 'media/gallery-08.jpg?v=1', 'details'),
  (8, 'media/gallery-09.jpg?v=1', 'details'),
  (9, 'media/gallery-10.jpg?v=1', 'details'),
  (10, 'media/gallery-11.jpg?v=1', 'details'),
  (11, 'media/gallery-12.jpg?v=1', 'details');

insert into peony_settings (key, value) values
  -- Adres ve telefon gerçek; ücret bilgileri hâlâ yer tutucu.
  ('phone', '+6633033689'),
  ('phone_display', '+66 33 033 689'),
  ('whatsapp', '+66 33 033 689'),
  ('email', 'hello@peonythaispa.com'),
  ('email_display', 'hello@peonythaispa.com'),
  ('address_line1', '193/137 Moo 10, Soi Buakhao'),
  ('address_line2', 'Pattaya City, Bang Lamung, Chon Buri 20150, Thailand'),
  ('hours_weekday', '10:00 – 22:00'),
  ('hours_weekend', '10:00 – 23:00'),
  ('instagram', '#'),
  ('facebook', '#'),
  ('whatsapp_url', 'https://wa.me/6633033689'),
  -- Pattaya, Soi Buakhao. Panelden başka bir konumla değiştirilebilir.
  ('map_embed', 'https://www.google.com/maps?q=193/137%20Moo%2010%2C%20Soi%20Buakhao%2C%20Pattaya%20City%2C%20Bang%20Lamung%20District%2C%20Chon%20Buri%2020150%2C%20Thailand&z=17&output=embed'),
  ('stat1', '11'),
  ('stat2', '11'),
  ('stat3', '1.111+'),
  ('hero_video', 'media/hero.mp4?v=1'),
  ('hero_poster', 'media/hero-poster.jpg?v=1'),
  ('about_inline', 'media/about-inline.jpg?v=1'),
  ('about_1', 'media/about-1.jpg?v=1'),
  ('about_2', 'media/about-2.jpg?v=1'),
  ('about_3', 'media/about-3.jpg?v=1'),
  ('ambience', 'assets/art/ambience-band.svg'),
  ('footer_bg', 'assets/art/footer-pattern.svg')
on conflict (key) do update set value = excluded.value;

-- Süreler gerçekçi, fiyatlar bariz sahte (tekrarlı rakam) — panelden değiştirilir.
update peony_services set duration = '60 / 90 dk', price = '฿1.111'
  where slug in ('thai','oil','aroma','herbal');
update peony_services set duration = '45 / 60 dk', price = '฿1.111'
  where slug in ('foot','scrub');
update peony_services set duration = '30 / 45 dk', price = '฿1.111' where slug = 'back';
update peony_services set duration = '60 dk',      price = '฿1.111' where slug = 'facial';

update peony_plans set price = '฿1.111', per = '/60 dk'  where position = 0;
update peony_plans set price = '฿2.222', per = '/90 dk'  where position = 1;
update peony_plans set price = '฿3.333', per = '/180 dk' where position = 2;
